# TODO: buildscan
# TODO: split into build.yml, gradle-wrapper-validation.yaml, dependency-submission.yml
# TODO: parameters to specify OS and JDK to run
# TODO: Caching for Gradle actions was disabled due to pre-existing Gradle User Home - expand for details

name: Java CI with Gradle

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  gradle-wrapper-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3

  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
        # See https://adoptium.net/temurin/archive/ for available versions
        # Available versions are: 8, 11, 16, 17, 18, 19, 20, 21, 22
        # The LTS versions are: 8, 11, 17, 21
        # We omit 8 because the class files in JGit require at least Java 11 (class file version 55.0)
        # We omit 22 because Kotlin does not yet support 22 JDK target
        java-version: [11, 16, 17, 18, 19, 20, 21]
        exclude:
          - # Java 16 is not available on MacOS for some reason
            runs-on: macos-latest
            java-version: 16

    runs-on: ${{ matrix.runs-on }}
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java-version }}
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
        build-scan-terms-of-use-agree: "yes"

    - name: Build with Gradle Wrapper
      run: ./gradlew build

  dependency-submission:
    strategy:
      fail-fast: false
      matrix:
        java-version: [17]

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java-version }}
        cache: gradle

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v3
      with:
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
        build-scan-terms-of-use-agree: "yes"
